# Copyright (c) 2021, Pete Batard <pete@akeo.ie>
# SPDX-License-Identifier: BSD-3-Clause

name: UEFI firmware - EDK2 build

on:  
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out EDK2 repositories
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/build
      with:
        version: ${{github.sha}}
    - name: Upload UEFI firmware artifacts
      uses: actions/upload-artifact@v2
      with:
        name: RPi4 UEFI Firmware ${{github.sha}} Artifacts
        path: |
          Build/RPi4/DEBUG_GCC5/FV/RPI_EFI.fd
          Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd
