# Copyright (c) 2021, Pete Batard <pete@akeo.ie>
# SPDX-License-Identifier: BSD-3-Clause

name: UEFI firmware - EDK2 build

on:  
  release:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Determine version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Check out EDK2 repositories
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/build
      with:
        version: ${{steps.version.VERSION}}
    - name: Upload UEFI firmware artifacts
      uses: actions/upload-artifact@v2
      with:
        name: RPi4 UEFI Firmware ${{steps.version.VERSION}} Artifacts
        path: |
          Build/RPi4/DEBUG_GCC5/FV/RPI_EFI.fd
          Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd
    - name: Download Raspberry Pi support files
      run: |
        curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/fixup4.dat
        curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/start4.elf
        curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/bcm2711-rpi-4-b.dtb
        curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/bcm2711-rpi-cm4.dtb
        curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/bcm2711-rpi-400.dtb
        curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/overlays/miniuart-bt.dtbo
        mkdir overlays
        mv miniuart-bt.dtbo overlays
    - name: Create UEFI firmware archive
      run: zip -r RPi4_UEFI_Firmware_${{inputs.version}}.zip RPI_EFI.fd *.dtb config.txt fixup4.dat start4.elf overlays Readme.md firmware
    - name: Display SHA-256
      run: sha256sum Build/RPi4/DEBUG_GCC5/FV/RPI_EFI.fd Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd RPi4_UEFI_Firmware_${{inputs.version}}.zip
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        draft: false
        prerelease: false
        release_name: ${{steps.version.VERSION}}
        body: Raspberry Pi 4 UEFI Firmware ${{steps.version.VERSION}}
        tag_name: ${{steps.version.VERSION}}
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_path: RPi4_UEFI_Firmware_${{steps.version.VERSION}}.zip
        asset_name: RPi4_UEFI_Firmware_${{steps.version.VERSION}}.zip
        asset_content_type: application/zip